---

---
title: "Sotera"
format: html
editor: visual
---

```{r setup}
library(tidyverse)
library(GGally)
knitr::opts_knit$set(root.dir = "/Users/barkerr7/Documents/Projects/Sotera-Sessler/SesslerClinicMonitoring/OneDrive_1_4-29-2024")
```

## Sotera Visi Analysis

Continuous Heart Rate and SPO2 Monitoring in post-surgical patients

## Analysis of Sotera Visi data (continuous monitoring of vital signs)

```{r load_data}
# Run clinical data file generator
folder=getwd()
source(paste0(folder,"/30037614241CRFV21FAC_R_2024-04-24_0737.r"))

baseline= read.csv(file='./baseline_20190121.csv')
Finalstudy =  read_csv(file='./Final_study_pop_20190107.csv')

# DO NOT USE read_csv for this file
monitoring = read.csv("./all_factor_visi_data.csv")

intra_op = read_csv("./intraop_20190121.csv")
```

```{r}
monitoring <- monitoring %>% rename(Study.ID=Study.ID.in.format....e.g..ppp.ss.nnnn.)
monitoring <- monitoring %>% mutate(across(c(SPO2, PR, RR, CNIBP_SYS,CNIBP_DIA, CNIBP_MAP, BP_SYS, BP_MAP, BP_DIA, HR), as.double))
```

```{r}
jama_p=read_csv("./primary_outcomes_jama_revision.csv")
jama_s =read_csv("./secondary_outcomes_20190211.csv")
```

Subset data into continuous (visi) and nurse observations

```{r}
monitor_n = monitoring |> filter(!is.na(BP_SYS)) %>% select(-CNIBP_SYS, -CNIBP_DIA, -CNIBP_MAP) 
monitor_v = monitoring |> filter(is.na(BP_SYS)) %>% select(-BP_SYS, -BP_DIA, -BP_MAP) %>% mutate(time = as_datetime(dev_reading_tm, format = "%d%b%Y:%H:%M:%S"))
```

```{r}
sotera_summary = monitor_v %>% filter(Study.ID!="") %>% group_by(Study.ID) %>% 
  summarise(as_tibble_row(quantile(SPO2, na.rm = TRUE), .name_repair=\(x) paste0('o2_q', parse_number(x))), 
            as_tibble_row(quantile(PR, na.rm=TRUE), .name_repair=\(x) paste0('PR_q', parse_number(x))),
            as_tibble_row(quantile(CNIBP_MAP, na.rm=TRUE), .name_repair=\(x) paste0('MAP_q', parse_number(x))),
            stay = max(time)-min(time))
            
nurse_summary = monitor_n  %>% filter(Study.ID!="") %>% group_by(Study.ID) %>% 
  summarise(mino2=min(SPO2), maxo2=max(SPO2), 
            minHR=min(PR), maxHR=max(PR), 
            minMAP=min(BP_MAP), maxMAP=max(BP_MAP),
            visits=n())

patient_summary = left_join(sotera_summary, nurse_summary)
patient_summary$randomization_number = as.integer(str_replace_all(patient_summary$Study.ID,'-',''))

patient_summary = left_join(patient_summary, baseline)
```

```{r}
intra_op_specific = intra_op %>% select(randomization_number,`Duration of surgery (hours)`, pacu_los_hr, `Type of Surgery`)

patient_summary <- left_join(patient_summary, intra_op_specific)
```

```{r}
patient_summary$o2_outlier = patient_summary$o2_q25-1.5*(patient_summary$o2_q75-patient_summary$o2_q25)

patient_summary$map_outlier = patient_summary$MAP_q25-1.5*(patient_summary$MAP_q75-patient_summary$MAP_q25)
```

```{r}
patient_summary$BMIHIGH=patient_summary$bmi>30
patient_summary$stay_hrs = patient_summary$stay/3600
```

```{r}
# Add empiric p-value difference

ggplot(data=patient_summary %>% filter(!is.na(mino2), !is.na(smoking_status))) + 
    geom_point( aes(x=o2_q0, y=mino2, col="Q0"))+ 
    geom_smooth(aes(x=o2_q0, y=mino2, col="Q0"), method = "lm")+
    geom_point( aes(x=o2_q25, y=mino2, col="Q25")) + 
    geom_smooth(aes(x=o2_q25, y=mino2, col="Q25"), method = "lm") + 
    facet_wrap("BMIHIGH")+
    xlab("Saturation Oxygen (Visi)") + ylab("Minimum Oxygen (Nurse)")
  
ggplot(data=patient_summary %>% filter(!is.na(minHR)))+
    geom_point(aes(x=PR_q0, y=minHR, col="Q0")) +
    geom_smooth(aes(x=PR_q0, y=minHR, col="Q0"), method = "lm")+
    geom_point( aes(x=PR_q25, y=minHR, col="Q25")) +  
    geom_smooth(aes(x=PR_q25, y=minHR, col="Q25"), method = "lm") + 
  facet_wrap("BMIHIGH")+ 
  xlab("PR (Visi)") + ylab("Minimum HR (Nurse)")

ggplot(data=patient_summary %>% filter(!is.na(minMAP), minMAP!=0))+
    geom_point(aes(x=MAP_q0, y=minMAP, col="Q0")) +
      geom_smooth(aes(x=MAP_q0, y=minMAP, col="Q0"), method = "lm") + 
      geom_point(aes(x=MAP_q25, y=minMAP, col="Q25")) +
      geom_smooth(aes(x=MAP_q25, y=minMAP, col="Q25"), method = "lm") + 
  facet_wrap("BMIHIGH")+ 
  xlab("MAP (Visi)") + ylab("Minimum MAP (Nurse)")#+ geom_abline(slope=1) 

```

```{r}
ggplot(data=patient_summary %>% filter(!is.na(smoking_status))) + geom_boxplot(aes(y=o2_q0, x=as.factor(smoking_status))) + xlab("Smoking Status") + ylab("Minimum Oxygenation (Continuous)")

kruskal.test(patient_summary$o2_q25, patient_summary$smoking_status)
```

```{r}
ggplot(data=patient_summary %>% filter(!is.na(asthma))) + geom_boxplot(aes(y=MAP_q0, x=as.factor(asthma))) + xlab("Asthma") + ylab("Min MAP (Continous)")

kruskal.test(patient_summary$MAP_q0, patient_summary$asthma)
```

```{r}
ggplot(data=patient_summary %>% filter(!is.na(asthma))) + geom_boxplot(aes(y=minMAP, x=as.factor(asthma))) + xlab("Asthma") + ylab("Min MAP (Nurse)")

kruskal.test(patient_summary$minMAP, patient_summary$asthma)
```

```{r}
ggplot(data=patient_summary %>% filter(!is.na(BMIHIGH))) + geom_boxplot(aes(y=mino2, x=as.factor(BMIHIGH))) + xlab("BMI>30") + ylab("Min Oxygenation (Nurse)")

kruskal.test(patient_summary$mino2, patient_summary$BMIHIGH)
```

```{r}

ggplot(data=patient_summary) + geom_point(aes(y=o2_q0, x=stay_hrs)) + xlab("Stay (hrs)") + ylab("Min SPO2 (Continuous)")
ggplot(data=patient_summary) + geom_point(aes(y=mino2, x=stay_hrs))
ggplot(data=patient_summary) + geom_point(aes(y=minMAP, x=stay_hrs))
ggplot(data=patient_summary) + geom_point(aes(y=MAP_q0, x=stay_hrs))
ggplot(data=patient_summary) + geom_point(aes(y=age, x=stay_hrs))+ xlab("Stay (hrs)") + ylab("Age")

ggplot(data=patient_summary) + geom_point(aes(y=bmi, x=stay_hrs))+ xlab("Stay (hrs)") + ylab("BMI")


```

```{r}


ggpairs(patient_summary %>% 
          select(stay_hrs, map_outlier, o2_outlier, PR_q0, age, bmi,
                 minMAP,mino2) %>% 
          mutate(across(c( stay_hrs, age, bmi,
                          minMAP,mino2),as.numeric)))
```

```{r}
library(GGally)
ggpairs(patient_summary  %>% 
          select(stay_hrs, age, bmi,
                 o2_q0,mino2,minMAP, MAP_q0, `Duration of surgery (hours)`, pacu_los_hr, gender) %>% 
          mutate(across(c(stay_hrs, age, bmi,
                          mino2,minMAP, MAP_q0,`Duration of surgery (hours)`,pacu_los_hr),as.numeric)) %>% filter(`Duration of surgery (hours)`<20) %>% filter(pacu_los_hr<20), ggplot2::aes(hue=gender))


```

```{r}
states <- c("high", "low", "critical")
nstates = 2
data = monitor_v %>% filter(Study.ID=="376-01-0095")
HMM_model <- depmixS4::depmix(data$SPO2~1, nstates=3, ntimes=length(data$SPO2))
HMM_fm <- depmixS4::fit(HMM_model)

summary(HMM_fm)

probs =depmixS4::posterior(HMM_fm)

summary(probs)

plot(data$SPO2, col=probs$state)
```

```{r}
i=63
data = monitor_v %>% filter(Study.ID==i)
HMM_model <- depmixS4::depmix(data$SPO2~1, nstates=3, ntimes=length(data$SPO2))
HMM_fm <- depmixS4::fit(HMM_model)
probs = depmixS4::posterior(HMM_fm)
params = depmixS4::getpars(HMM_fm)

```

```{r}
patient_summary$T1 = 0
patient_summary$T2 = 0
patient_summary$T3 = 0
```

```{r}

for (i in 1:length(patient_summary$Study.ID)){
  print(i)
  data = monitor_v %>% filter(Study.ID==patient_summary$Study.ID[i])
  HMM_model <- depmixS4::depmix(data$SPO2~1, nstates=3, ntimes=length(data$SPO2))
  if (length(data$SPO2)>0){
    HMM_fm <- depmixS4::fit(HMM_model)
    probs = depmixS4::posterior(HMM_fm)
    params = depmixS4::getpars(HMM_fm)
  }
  else{
    params=c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
  }
  patient_summary$T1[i] = params[4]
  patient_summary$T2[i] = params[8]
  patient_summary$T3[i] = params[12]
}
```

```{r}
correlations_HRBP = c()
correlations_RRO2 = c()
for (i in patient_summary$Study.ID){
  #print(i)
  data = monitor_v %>% filter(Study.ID==i)
  #plot = ggplot(aes(x=HR, y=CNIBP_MAP), data=data)+ geom_point()
  #ggsave(filename = paste0(i,"cor.png"), plot=plot)
  if (){
    valHRBP=cor.test(data$PR, data$CNIBP_MAP)
    valRRO2=cor.test(data$PR, data$SPO2)
    correlations_HRBP = c(correlations_HRBP, valHRBP$estimate)
    correlations_RRO2 = c(correlations_RRO2, valRRO2$estimate)
  }
  else{
    correlations_HRBP = c(correlations_HRBP, NA)
    correlations_RRO2 = c(correlations_RRO2, NA)
  }

  }
```

```{r}
model1=glm(formula = asa ~ o2_q0 + o2_outlier + map_outlier+ MAP_q0+PR_q50+T1+age+bmi, data = patient_summary %>% mutate(across(c(stay_hrs, age, bmi,
                          mino2, MAP_q0),as.numeric)))
model2=glm(formula = asa ~ age+ bmi, data = patient_summary %>% mutate(across(c(stay_hrs, age, bmi, mino2, MAP_q0),as.numeric)))


myroc <- pROC::roc(patient_summary$asa,predict(model1, patient_summary %>% mutate(across(c(stay_hrs, age, bmi,mino2, MAP_q0),as.numeric)), type = "response")) 
myroc2 <- pROC::roc(patient_summary$asa,predict(model2, patient_summary %>% mutate(across(c(stay_hrs, age, bmi,mino2, MAP_q0),as.numeric)), type = "response")) 

plot(myroc)
plot(myroc2, add=TRUE)

```

```{r}
glm(formula = stay_hrs ~ MAP_q0+ o2_q0 +T1+ age + bmi+gender, data = patient_summary %>% mutate(stay_hrs = as.numeric(stay_hrs)))
```

T

```{r}

ggpairs(patient_summary %>% 
          select(o2_q0, o2_q25, stay_hrs, age, bmi,mino2, smoking_status, gender, race) %>% 
          filter(!is.na(smoking_status), !is.na(race)) %>%
          mutate(across(c(o2_q0, o2_q25, 
                          stay_hrs, age, bmi, mino2),as.numeric)) %>% 
          mutate(across(c(gender, smoking_status), as.factor)), ggplot2::aes(colour=smoking_status))
```

```{r}
patient_summary
```
